### ISSUE TITLE
"./configure --disable-aes" fails to build on v1.2.41

### ISSUE THREAD

**Issue by jmossber-vc** [lsh123/xmlsec#918]
```
ciphers.c: In function ‘xmlSecOpenSSLEvpBlockCipherCtxFinal’:
ciphers.c:609:16: warning: implicit declaration of function ‘xmlSecOpenSSLEvpBlockCipherGCMCtxFinal’; did you mean ‘xmlSecOpenSSLEvpBlockCipherCBCCtxFinal’? [-Wimplicit-function-declaration]
  609 |         return xmlSecOpenSSLEvpBlockCipherGCMCtxFinal(ctx, in, out, cipherName, transformCtx);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                xmlSecOpenSSLEvpBlockCipherCBCCtxFinal
```

**Comment by lsh123** [comment]
* Master: https://github.com/lsh123/xmlsec/pull/921
* 1.2.x branch: https://github.com/lsh123/xmlsec/pull/922

Please consider switching to xmlsec 1.3.x since the 1.2.x is in maintenance mode (https://github.com/lsh123/xmlsec/blob/master/SECURITY.md)
